# Generated by Django 6.0.4 on 2026-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('man', 'Man'), ('women', 'Women')])),
                ('adress', models.CharField()),
                ('course', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('react', 'React')])),
                ('photo', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
